# Determinant and the Cramer's rule

by Xiaofeng Liu, Ph.D., P.E.
Associate Professor

Department of Civil and Environmental Engineering

Institute of CyberScience

Penn State University 

223B Sackett Building, University Park, PA 16802

Web: http://water.engr.psu.edu/liu/

---

## The Cramer's rule

The Cramer's rule is a brutal force method to get the solution of a linear equation system. 

For a linear equation system $\mathbf{Ax}=\mathbf{b}$, the solution is given by 
  \begin{equation}
  x_i = \frac{det{A_i}}{det{A}}
  \end{equation}
  where $A_i$ is the matrix formed by replacing the $i$-th column of $A$ with the column vector $\mathbf{b}$.

For example, for a $3 \times 3$ system,

 \begin{equation}
x_1 = \frac{
 \left|
\begin{array}{ccc}
  b_1 & A_{11} & A_{13}  \\
  b_2 & A_{21} & A_{23}  \\
  b_3 & A_{31} & A_{33}      
\end{array}
\right|
}{D} 
 \end{equation}

 \begin{equation}
x_2 = \frac{
 \left|
\begin{array}{ccc}
  A_{11} & b_1 & A_{13}  \\
  A_{21} & b_2 & A_{23}  \\
  A_{31} & b_3 & A_{33}      
\end{array}
\right|
}{D} 
 \end{equation}
 
  \begin{equation}
x_2 = \frac{
 \left|
\begin{array}{ccc}
  A_{11} & A_{13} & b_1  \\
  A_{21} & A_{23} & b_2  \\
  A_{31} & A_{33} & b_3     
\end{array}
\right|
}{D} 
 \end{equation}



An example linear equation system is as follows:

\begin{equation}
\mathbf{A} \mathbf{x} = \mathbf{b}
\end{equation}

\begin{equation}
\begin{bmatrix}
1  & 3  & 2 \\
5  & 8  & 7 \\
0  & -2 & 10 
\end{bmatrix}
\begin{bmatrix}
x_0 \\
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
1 \\
4 \\
5
\end{bmatrix}
\end{equation}

In the following code, it is solved by both the Cramer's rule and the "linalg" module in Numpy. The solutions are compared.

In [35]:
import numpy as np
from numpy import linalg
import sys

#replace the col-th column with b vector and assign
#it to array C
def replace_column(col, b, A, C):
    if(b.shape[0]!=A.shape[0]):
        sys.exit("The sizes of vector b and array A are not compatible.")
        
    if(A.shape[0]!=A.shape[1]):
        sys.exit("A is not a square matrix!")
        
    n = A.shape[0]
    
    #copy matrix A to C
    np.copyto(C, A) 
    
    #replace the col-th column with the vector b
    for i in range(0,n):
        C[i,col] = b[i]
    
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

C = np.zeros((len(b),len(b)))

sol = []
for i in range(0,len(b)):
    replace_column(i,b,A,C)
    sol.append(round(linalg.det(C)/linalg.det(A),8))

print("Solution from the Cramer's rule =    ", sol)

x = np.linalg.solve(A,b)      #solve with the "solve(...)" function in Numpy.
print("Solution from np.linalg.solve(...) = ", x)

Solution from the Cramer's rule =     [0.22368421, -0.06578947, 0.48684211]
Solution from np.linalg.solve(...) =  [ 0.22368421 -0.06578947  0.48684211]


In [50]:
from scipy.linalg import lu_factor

A = np.array([[5,2],[4,3]])
print(A)

lu, piv = lu_factor(A)
lu

L = np.array([[1,0],[0.8,1]])
U = np.array([[5,2],[0,1.4]])

print(L.dot(U))


[[5 2]
 [4 3]]
[[5. 2.]
 [4. 3.]]


In [42]:
from scipy.linalg import lu_factor
from numpy import tril, triu, allclose, zeros, eye

A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
lu, piv = lu_factor(A)
piv

array([2, 2, 3, 3], dtype=int32)