# Iterative solution methods

by Xiaofeng Liu, Ph.D., P.E.
Associate Professor

Department of Civil and Environmental Engineering

Institute of CyberScience

Penn State University 

223B Sackett Building, University Park, PA 16802

Web: http://water.engr.psu.edu/liu/

---

This notebook is a demonstration of iterative solution methods for solving linear equation system.

## Jacobi method

For linear equation system 
	\begin{equation}
	\mathbf{Ax=b}
	\end{equation} 
	where the matrix $\mathbf{A}$ can be written as the sum of a diagonal matrix $\mathbf{D}$ and the remainder matrix $\mathbf{R}$, i.e.,
	\begin{equation}
	\mathbf{A = D + R}
	\end{equation}
    
\begin{equation}
D = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ 0 & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & a_{nn} \end{bmatrix} \text{ and } R = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ a_{21} & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & 0 \end{bmatrix}
\end{equation}

The Jacobi iteration is then
	\begin{equation}
	\mathbf{x}^{(k+1)} = \mathbf{D}^{-1} (\mathbf{b} - \mathbf{R} \mathbf{x}^{(k)})
	\end{equation}
where $k$ is the iteration number, $k \in [0,1,2,\cdots]$. 
	Note the inverse of the diagonal matrix $\mathbf{D}$ is easy because
	\begin{equation}
\mathbf{D}^{-1} = \begin{bmatrix} 1/a_{11} & 0 & \cdots & 0 \\ 0 & 1/a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & 1/a_{nn} \end{bmatrix} 
\end{equation}
	To start the iteration, we need an initial guess $\mathbf{x}^0$.

In [12]:
import numpy as np    


#maximum number of iterations
max_iter = 1000

#stopping criterion
eps_c = 1e-6

#define the matrix and vector
A = np.array([[10.8,2.1,2.9], [3.1,-10.5,2.1], [-2.1,3.1,8.1]])  #diagonal domimant; it converges
#A = np.array([[1.8,2.1,2.9], [3.1,-1.5,2.1], [-2.1,3.1,2.1]])  #not diagonal dominant; it will diverge
b = np.array([6.0,-12.0,26.0])

print("A = \n", A)

#initial guess for x
x = np.array([1,1,1])
x_new = x

#extract the diagonal matrix of A
D = np.diag(np.diag(A))
print("D = \n", D)

R = A - D
print("R = \n", R)

for i in range(max_iter):
    #print("iteration ", i)
    x_new = np.linalg.inv(D).dot(b-R.dot(x))
    x=x_new
    
    error = np.linalg.norm(np.dot(A,x_new) - b)/np.linalg.norm(b)
    if(error<eps_c):
        print("converged at iteration ", i)
        break;

#print out solution
print("solution = ", x)

A = 
 [[ 10.8   2.1   2.9]
 [  3.1 -10.5   2.1]
 [ -2.1   3.1   8.1]]
D = 
 [[ 10.8   0.    0. ]
 [  0.  -10.5   0. ]
 [  0.    0.    8.1]]
R = 
 [[ 0.   2.1  2.9]
 [ 3.1  0.   2.1]
 [-2.1  3.1  0. ]]
converged at iteration  17
solution =  [-0.41699705  1.5234845   2.51870298]


## Gauss-Seidel method

The matrix notation of the Gauss-Seidel method is as follows. The matrix $\mathbf{A}$ is decomposed into a lower triangular matrix $\mathbf{L}$ and a strictly upper triangular  matrix $\mathbf{U}$: $\mathbf{A=L+U}$.
\begin{equation}
\mathbf{L} = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ a_{21} & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}, \quad \mathbf{U} = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ 0 & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & 0 \end{bmatrix}.
\end{equation}	
The original linear system can be written as
\begin{equation}
 \mathbf{Lx} = \mathbf{b} - \mathbf{Ux}
\end{equation}
and the iteration formula is
\begin{equation}
\mathbf{x}^{(i+1)} = \mathbf{L}^{-1} (\mathbf{b} - \mathbf{U} \mathbf{x}^{(i)})
\end{equation}

In [11]:
import numpy as np    


#maximum number of iterations
max_iter = 1000

#stopping criterion
eps_c = 1e-6

#define the matrix and vector
A = np.array([[10.8,2.1,2.9], [3.1,-10.5,2.1], [-2.1,3.1,8.1]])  #diagonal domimant; it converges
#A = np.array([[1.8,2.1,2.9], [3.1,-1.5,2.1], [-2.1,3.1,2.1]])  #not diagonal dominant; it will diverge
b = np.array([6.0,-12.0,26.0])

print("A = \n", A)

#initial guess for x
x = np.array([1,1,1])
x_new = x

#extract the lower and strictly upper triangular matrices L and U
#see documentation for the functions tril and triu in Numpy.
L = np.tril(A,0)
U = np.triu(A,1)

print("L = \n", L)
print("U = \n", U)

for i in range(max_iter):
    #print("iteration ", i)
    x_new = np.linalg.inv(L).dot(b-U.dot(x))
    x=x_new
    
    error = np.linalg.norm(np.dot(A,x_new) - b)/np.linalg.norm(b)
    if(error<eps_c):
        print("converged at iteration ", i)
        break;

#print out solution
print("solution = ", x)

A = 
 [[ 10.8   2.1   2.9]
 [  3.1 -10.5   2.1]
 [ -2.1   3.1   8.1]]
L = 
 [[ 10.8   0.    0. ]
 [  3.1 -10.5   0. ]
 [ -2.1   3.1   8.1]]
U = 
 [[0.  2.1 2.9]
 [0.  0.  2.1]
 [0.  0.  0. ]]
converged at iteration  6
solution =  [-0.41699685  1.52348497  2.5187041 ]
