# Linear equation systems

by Xiaofeng Liu, Ph.D., P.E.
Associate Professor

Department of Civil and Environmental Engineering

Institute of Computational and Data Sciences

Penn State University 

223B Sackett Building, University Park, PA 16802

Web: http://water.engr.psu.edu/liu/

---

## Introduction

In the root finding methods chapter, we discussed how to find the roots of a single equation. In many applications, we need to find the roots of many simultaneous equations. In this chapter, we will learn how to solve simultaneous linear equations, or linear equation systems (LES) in the form of
\begin{eqnarray*}
  a_{11} x_1 + a_{12} x_2 + a_{13} x_3 + \cdots + a_{1n} x_n &=& b_1\\
  a_{21} x_1 + a_{22} x_2 + a_{23} x_3 + \cdots + a_{2n} x_n &=& b_2\\
   \vdots  &=& \vdots   \\
  a_{n1} x_1 + a_{n2} x_2 + a_{n3} x_3 + \cdots + a_{nn} x_n &=& b_n  
\end{eqnarray*}

Linear equation systems are used in many applications. In the following, we will introduce several such applications, most of which are relevant to CEE. 

- Regression analysis

One application is for polynomial regression we learned in last chapter. To perform polynomial regression, one can solve the normal equation. Recall for a second-order polynomial regression, the linear equation system for the regression coefficients is:
\begin{equation}
\begin{bmatrix}
(n) & \left(\sum x_i \right) & \left(\sum x_i^2 \right) \\
\left(\sum x_i \right) & \left(\sum x_i^2 \right) & \left(\sum x_i^3 \right) \\
\left(\sum x_i^2 \right) & \left(\sum x_i^3 \right) & \left(\sum x_i^4 \right)
\end{bmatrix}
\begin{bmatrix}
a_0 \\
a_1 \\
a_2
\end{bmatrix}
=
\begin{bmatrix}
\sum y_i \\
\sum x_i y_i \\
\sum x_i^2 y_i
\end{bmatrix}
\end{equation}  

- Traffic flow problem
In the analysis of traffic flow and pattern for certain area, we need to calculate the traffice (cars/day) for each street in the area. For example, the figure below shows the idea. Based on conservation law (in and out traffic flow in balance for each street intersection), the governing equation for eaach intersection can be written as
   - For intersection $A$:  $480-x_1-x_4=0$
   - For intersection $B$:  $x_1-250-x_2=0$
   - For intersection $C$:  $x_2+530-220-x_3=0$
   - For intersection $D$:  $x_4+x_3-330-210=0$
   
Here we have four unknowns ($x_1,x_2,x_3,x_4$) with four linear equations, which can be written in matrix form as
\begin{equation}
\begin{bmatrix}
-1 & 0 & 0 & -1 \\
1 & -1 & 0 & 0  \\
0 &  1 & -1 & 0  \\
0 &  0 & 1 & 1 
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\ 
x_3 \\ 
x_4 
\end{bmatrix}
=
\begin{bmatrix}
-480\\
250\\
-310\\
540
\end{bmatrix}
\end{equation}
Solving this linear equation system will give the unknown traffic flows.

<img src="traffic_example.png" width="300"/>
<h3 align="center">Figure. Traffic flow problem.</h3> 

- Truss analysis

For the truss system shown in the following figure, what are the forces in each of the beams? The two loading forces $F_C$ and $F_E$ are acting at joints $C$ and $E$, respectively. Gravity force is ignored. This problem can be solved with the force balance at each joint.  For example for joint B (assume all compress forces):
   - in $x$-direction:  $\frac{1}{\sqrt{2}}f_1 - f_5 = 0$
   - in $y$-direction:  $\frac{1}{\sqrt{2}}f_1 + f_3 = 0$
There are eight beams in the truss. In addition, there are four reaction forces at $A$ and $F$ (two each). So there are twelve unknown forces. We can write the force balance for eacho of the joints. In the end, we have the following linear equation system:
\begin{equation}
\begin{bmatrix}
1 & 0 & -1/\sqrt{2} & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & -1/\sqrt{2} & 0  & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1/\sqrt{2} & 0 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1/\sqrt{2} & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1  & 0 & -1 & 0& 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0  & -1 & 0& 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0  & 0 & 0 & 1 & 0 &-1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0  & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0  & 0 & 1 & 0 & 0 & 0 & -1/\sqrt{2} & 0 & 0 \\
0 & 0 & 0 & 0  & 0 & 0 & 0 &-1 & 0 & -1/\sqrt{2} & 0 & 0 \\
0 & 0 & 0 & 0  & 0 & 0 & 0 & 0 & 1 & 1/\sqrt{2} & 1 & 0 \\
0 & 0 & 0 & 0  & 0 & 0 & 0 & 0 & 0 & 1/\sqrt{2} & 0 & 1 
\end{bmatrix}
\begin{bmatrix}
R_A \\
N_A \\ 
f_1 \\ 
f_2 \\ 
f_3 \\ 
f_4 \\ 
f_5 \\ 
f_6 \\ 
f_7 \\ 
f_8 \\ 
R_F \\ 
N_F 
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0\\
0\\
0\\
F_C\\
0\\
0\\
0\\
F_E\\
0\\
0
\end{bmatrix}
\end{equation}
The matrix on the left is $12 \times 12$ because of we have 12 unknowns and the right hand side is the load vector which only involves the loading at joints $C$ and $E$. Solving this linear equation system will give the 12 unknown forces. 

<img src="truss_example.png" width="300"/>
<h3 align="center">Figure. Forces in truss problem.</h3> 

- Reactors system example
Chemical reactors can be connected and combined into a system. Inflows with different chemical composition and concentrations can be mixed and react. The final product will be exported as an outflow. In the example shown the following figure, only mixing is considered and no reaction happens in each of the reactor. For simplicity, we only consider one chemical species only. The principle can be expanded into multiple species. If there are reaction in the reactors, the following analysis does not apply. 

Three reactors are connected as follows. The flow rates into and out of the system, as well as inbetween the reactors, are given. The question is what the concentrations in each reactor will be at steady state. To solve this problem, we can use simple mass conservation law for the chemical species in each reactor: incoming = outgoing. For reactor 1, 2, and 3, respectively, we have the following species mass balance:
\begin{equation}
2 \times 1 + 1 \times C_2 = 3 \times C_1
\end{equation}

\begin{equation}
5 \times 3 = 1\times C_2 + 4\times C_2
\end{equation}
 
\begin{equation}
3 \times C_1 + 4 \times C_2 = 7 \times C_3
\end{equation}

<img src="reactor_system.png" width="300"/>
<h3 align="center">Figure. Reactors system example.</h3> 

The resulted linear system has the form of: 
\begin{eqnarray}
  2 + C_2 &=& 3 C_1 \\
  15 & = & 5 C_2 \\
  3C_1 + 4 C_2 &=& 7 C_3
\end{eqnarray}
which can be written in matrix form as:
 \begin{equation}
 \begin{bmatrix}
  -3 & 1  & 0 \\
  0  & 5  & 1 \\
  3 & 4 & -7 \\
 \end{bmatrix}
 \begin{bmatrix}
 c_1 \\
 c_2 \\
 c_3 
 \end{bmatrix}
=
\begin{bmatrix}
-2 \\
15 \\
0 
\end{bmatrix} 
 \end{equation}
The solution of this linear equation system will give the concentrations in each of the three reactors at steady state.

- Concrete mixture example
Concrete mixture is made of cement, sand, and gravel (before water is added). A common problem is mix different concrete mixture to achieve certian cement, sand and gravel ratio. For example, a contractor wants 100 cubic feet of mixture with cement:sand:gravel = 1:2:3. The contractor has three suppliers who can supply mixtures as follows:
   - Supplier 1: cement:sand:gravel = 1:3:4
   - Supplier 2: cement:sand:gravel = 1:2:5
   - Supplier 3: cement:sand:gravel = 1:3:2        
The question is how much the contractor needs to buy from each supplier to achieve his goal? To solve this problem, let's define $x_1$, $x_2$, and $x_3$ as the volume to buy from each supplier. Then, the total volume should satisfy
\begin{equation}
   x_1 + x_2 + x_3 = 100
\end{equation}

The total cement, sand, and gravel he will get can be calculated as follows:
   - Total cement: $\frac{1}{8}x_1 + \frac{1}{8}x_2 +\frac{1}{6}x_3 $
   - Total sand: $\frac{3}{8}x_1 + \frac{2}{8}x_2 +\frac{3}{6}x_3 $
   - Total gravel: $\frac{4}{8}x_1 + \frac{5}{8}x_2 +\frac{2}{6}x_3 $
Then the desired ratio of cement:sand:gravel = 1:2:3 gives
 \begin{equation}
  2\left(\frac{1}{8}x_1 + \frac{1}{8}x_2 +\frac{1}{6}x_3 \right) = \frac{3}{8}x_1 + \frac{2}{8}x_2 +\frac{3}{6}x_3  
 \end{equation}
 \begin{equation}
 3 \left(\frac{1}{8}x_1 + \frac{1}{8}x_2 +\frac{1}{6}x_3 \right) = \frac{4}{8}x_1 + \frac{5}{8}x_2 +\frac{2}{6}x_3
 \end{equation}
 
After simplification, the problem can be written as
\begin{eqnarray}
 x_1 + x_2 + x_3 &=& 100 \\
 3 x_1 - 4 x_3 &=& 0 \\
 9x_1+6x_2-4x_3 & = & 0
 \end{eqnarray}
or in matrix form as
 \begin{equation}
 \begin{bmatrix}
  1 & 1  & 1 \\
  3 & -4 & 0  \\
  9 & 6  & -4
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3
 \end{bmatrix}
=
\begin{bmatrix}
100 \\
0 \\
0
\end{bmatrix} 
 \end{equation}
 
 - Linear equation system resulted from the solution of differential equations
 This type of application is not as obvious as the previous examples. However, it is probably more important than anything else. Differential equations are used extensive in CEE to describe many processes of interest. These differential equations are usually solved numerically with a computer. Numerical solution of differential equations is the core of many software used in civil and environmental engineering, for example
- structure analysis: finite element method (FEM)
- hydraulics: HEC-RAS and SRH-2D using finite volume method (FVM)
 
Most of these computer software discretize the governing equations, such as conservation of mass, momentum, and energy, on mesh elements or points. The resulted discretized governing equations on mesh elements or points form a linear equations system:
\begin{equation}
\mathbf{Ax=b}
\end{equation} 
where $\mathbf{A}$ is a matrix, $\mathbf{x}$ is the unknown vector, and $\mathbf{b}$ is the right hand side vector. We have one chapter later this book to introduce the solution of partitial differential equations. 

Here, a simple heat tranfer in a rod example is used to demonstrate the point of linear equation system and its place in the solution of differential equations (Versteeg and Malalasekera, 2007). The governing equation has the simple form of
\begin{equation}
    \frac{d}{dx} \left( k \frac{dT}{dx} \right) = 0
\end{equation}
where $k$ is the heat transfer coefficient, $T$ is temperature, and $x$ is coordinate. 
Assume the rod is 0.5 m long, with a cross sectional area of $10\times 10^{-3}$ m$^2$, and $k=1000$ $W/m/K$. The boundary conditions are: $T_A$ = 100 K and $T_B$ = 500 K.

<img src="heat_1d_rod.png" width="600"/>
<h3 align="center">Figure. Steady-state 1D heat transfer in a rod.</h3> 

Divide the rod into 5 equal-length pieces and discretize the governing equation on each of will result in 5 linear equations. The resulted linear equations system can be written in matrix form as:
\begin{equation}
\begin{bmatrix}
  300 & -100 &       0 & 0 & 0 \\
 -100 &  200 & -100 & 0 & 0 \\
  0 & -100 & 200 & -100 & 0 \\
  0 & 0 & -100 & 200 & -100 \\
  0 & 0 & 0 & -100 & 300 \\
\end{bmatrix} \left[\begin{array}{c}
                T_1 \\
                T_2 \\
                T_3 \\
                T_4 \\
                T_5
              \end{array}\right] =
               \left[\begin{array}{c}
                20000 \\
                0 \\
                0 \\
                0 \\
                100000
              \end{array}\right]
\end{equation} 

Solution of this linear equation system will give the temperature at the center of each piece (cell). 


## A brief review of matrix and vector operations

The solution of linear equation system heavily involves matrix and vector operations. This section briefly reviews the important operations in prepaaration in the introdcution of solution methods. In the appendix, a short tutorial is provided for how to perform matrix and vector operations in Python.

A matrix $\mathbf{A}$ with $m$ rows and $n$ columns can be denoted as $A_{m \times n}$. Elements (entries) of matrix $A$ can be written as $A_{i,j},i\in[1,m],j\in [1,n]$. 

 \begin{equation}
 A = 
 \begin{bmatrix}
  A_{11} & A_{12}  & A_{13} & \cdots & A_{1n} \\
  A_{21} & A_{22}  & A_{23} & \cdots & A_{2n} \\
  A_{31} & A_{32}  & A_{33} & \cdots & A_{3n} \\    
  \cdots & \cdots  & \cdots & \cdots & \cdots\\
  A_{m1} & A_{m2}  & A_{m3} & \cdots & A_{mn}
 \end{bmatrix}
 \end{equation}

There are some special notes for matrix:
- the diagonal of matrix $A$ is $A_{i,i}$.
- a matrix ia a square matrix if $m=n$
- a matrix is a symmetric| matrix if it is a square matrix with $A_{i,j}=A_{j,i}$
- a matrix is a diagonal matrix if it is a square matrix with only none zero elements on its diagonal.
\begin{equation}
 A = 
 \begin{bmatrix}
  A_{11} & 0  & 0 & \cdots & 0 \\
  0      & A_{22}  & 0   & \cdots & 0 \\
  0 & 0  & A_{33} & \cdots & 0 \\    
  \cdots & \cdots  & \cdots & \cdots & \cdots\\
  0 & 0  & 0 & \cdots & A_{mm}
 \end{bmatrix}
\end{equation}
- a matrix is a identity matrix if it is a diagonal matrix with all diagonal elements equal to 1.
\begin{equation}
  I = 
 \begin{bmatrix}
  1 & 0  & 0 & \cdots & 0 \\
  0   & 1  & 0   & \cdots & 0 \\
  0 & 0  & 1 & \cdots & 0 \\    
  \cdots & \cdots  & \cdots & \cdots & \cdots\\
  0 & 0  & 0 & \cdots & 1
 \end{bmatrix}
 \end{equation} 
- upper/lower triangular matrix is a square matrix with all elements below/above its diagonal equal to 0.

 \begin{equation}
 Upper = 
 \begin{bmatrix}
  A_{11} & A_{12}  & A_{13} & \cdots & A_{1m} \\
  0 & A_{22}  & A_{23} & \cdots & A_{2m} \\
  0 & 0  & A_{33} & \cdots & A_{3m} \\    
  \cdots & \cdots  & \cdots & \cdots & \cdots\\
  0 & 0  & 0 & \cdots & A_{mm}
 \end{bmatrix}
 \end{equation}
 
 
 \begin{equation}
 Lower = 
 \begin{bmatrix}
  A_{11} & 0    & 0   & \cdots & 0  \\
  A_{21} & A_{22}  & 0 & \cdots & 0 \\
  A_{31} & A_{32}  & A_{33} & \cdots & 0 \\    
  \cdots & \cdots  & \cdots & \cdots & \cdots\\
  A_{m1} & A_{m2}  & A_{m3} & \cdots & A_{mm}
 \end{bmatrix}
 \end{equation} 

Operations can be defined for a matrix. The following shows some examples:
- matrix addition/subtraction with another matrix: it is defined as an element-by-element operation. In this case the dimensions of the two matrix must match. For example,
  
\begin{equation}
 \begin{bmatrix}
  A_{11} & A_{12}  \\
  A_{21} & A_{22} 
 \end{bmatrix}
 +
  \begin{bmatrix}
  B_{11} & B_{12}  \\
  B_{21} & B_{22}
   \end{bmatrix}
  =
   \begin{bmatrix}
  A_{11}+B_{11} & A_{12}+B_{12}  \\
  A_{21}+B_{21} & A_{22}+B_{22} 
 \end{bmatrix}
 \end{equation}
 
- scaling of a matrix (multiplication with a scalar): each element of the matrix is scaled. For example, 
\begin{equation}
 \alpha \begin{bmatrix}
  A_{11} & A_{12}  \\
  A_{21} & A_{22} 
 \end{bmatrix}
  =
   \begin{bmatrix}
 \alpha A_{11} & \alpha A_{12}  \\
 \alpha A_{21} & \alpha A_{22} 
 \end{bmatrix}
 \end{equation}
 
- matrix multiplication with another matrix: first matrix's number of columns = second matrix's number of rows. 
\begin{equation}
A_{m,n}B_{n,k} = C_{m,k}
\end{equation}  

\begin{equation}
C_{m,k} = \sum\limits_{i=1}^n A_{m,i} B_{i,n}
\end{equation}  
A special case of matrix-matrix multiplication is for identity matrix:
\begin{equation}
A I = I A = A
\end{equation}  

- the inverse of a matrix $A^{-1}$ is defined as 
\begin{equation}
  A A^{-1} = A^{-1} A = I
\end{equation}

- matrix transposition $A^T$ is defined such that
\begin{equation}
 A^T = \begin{bmatrix}
  A_{11} & A_{12}  \\
  A_{21} & A_{22} 
 \end{bmatrix}^T
 =
  \begin{bmatrix}
  A_{11} & A_{21}  \\
  A_{12} & A_{22} 
 \end{bmatrix}
\end{equation}

- matrix augmentation is defined to add one or more columns to the matrix. It is used in some solution method with row operations. For example,     
\begin{equation}
\begin{bmatrix}
  A_{11} & A_{12} & 1  & 0  \\
  A_{21} & A_{22} & 0  & 1
 \end{bmatrix}
 \end{equation}
 
- row vector and column vector are defined as follows:
 \begin{equation}
 b = [b_1, b_2, b_3, ..., b_n]
 \end{equation}

 \begin{equation}
 b = 
 \begin{bmatrix}
 b_1 \\
 b_2 \\
 b_3 \\
 \vdots \\
 b_n
 \end{bmatrix}
 \end{equation} 

## Categories of solution methods for linear equation system

There are three categories of solutions methods we will discuss. 
- Graphical method
- Direct solution methods
- Iterative solution methods.

The focus will be the latter two.


### Graphical method

Similar to our discussion in the root finding chapter, graphical method is not often used in practice. However, its value is to illustrate some important concepts related to linear systems. Since graphs can only be drawn in 2D or 3D space, graphical method can only be used for a system with 2 or 3 equations. 

Consider a system with two equations as follows:
\begin{eqnarray}
  A_{11} x_1 + A_{12}x_2 & = & b_1 \\
  A_{21} x_1 + A_{22}x_2 & = & b_2
\end{eqnarray}
The two equations represent two straight lines in a Cartesian coordinate system:
\begin{eqnarray}
  x_2 & = & -\frac{A_{11}}{A_{12}} x_1 + \frac{b_1}{A_{12}} \\
  x_2 & = & -\frac{A_{21}}{A_{22}} x_1 + \frac{b_2}{A_{22}}
\end{eqnarray}

The solution of the linear equation system is at the intersection of the two straight lines as shown in the following figure. 
<img src="graphical_method.png" width="300"/>
<h3 align="center">Figure. Graphical representation of a linear equation system with two equations.</h3> 

It is easy to imagine that the intersection does not always exist. From the figure below, there are several solution scenarios:
- one unique solution if the matrix $A$ is not singular
- no solution and infinite solution if $A$ is singular and $det(A)$ = 0. 
- ill-conditioned if $A$ is close to singular. Solution is not stable. 
  
<img src="graphical_method_solutions.png" width="500"/>
<h3 align="center">Figure. Graphical representation of solution scenarios for a linear equation system with two equations.</h3> 

Linear equation systems with more than three equations have similar solution scenarios although it is impossible to visualize in high-dimensional spaces. 

### Direct solution methods

Direct solution methods solve the linear equation system directly, instead of iteratively. They produce the solution with finite number of operations. For large linear equation system, the required number of operations is also large and thus direct solution methods are computationally costly for large systems. For this reason, in reality, direct solution methods are often used for small to medium size systems. New computing techniques, such as parallel computing and GPU computing may greatly improve the computational efficiency of direct methods. 

In theory, if there is no rounding error, the solution from direct methods should be exact. A more attractive feature of direct methods is that the solution is guaranteed if the system is not singular. In contrast, most of iterative methods can not guarantee the same. So for some mission critical systems where a guarantee of solution is a must, direct solution methods are the only choices. 

Example direct solution methods include the following:
- Cramer's rule
- Gaussian elimination method
- Gauss-Jordan method
- LU factorization method

#### Determinant and Cramer's rule
The determinant $D$ of a matrix $A$ is a scalar value, usually noted as $det(A)$. Notice the difference in the notation of bracket and vertical straight lines in matrix and its determinant as follows:
       \begin{equation}
       A = 
\begin{bmatrix}
  A_{11} & A_{12} & A_{13}  \\
  A_{21} & A_{22} & A_{23}  \\
  A_{31} & A_{32} & A_{33}  
 \end{bmatrix}
 \end{equation}
 
 \begin{equation}
 D = det(A) =
\left|
\begin{array}{ccc}
  A_{11} & A_{12} & A_{13}  \\
  A_{21} & A_{22} & A_{23}  \\
  A_{31} & A_{32} & A_{33}  
\end{array}
\right|
 \end{equation}
 
For a $2 \times 2$ matrix, its determinant is
   \begin{equation}
 D = 
\left|
\begin{array}{cc}
  A_{11} & A_{12}  \\
  A_{21} & A_{22} 
\end{array}
\right|
  = 
  A_{11}A_{22} - A_{12}A{21}
 \end{equation} 
 
For a $3 \times 3$ matrix, its determinant is

   \begin{eqnarray}
 D &=& \left|
\begin{array}{ccc}
  A_{11} & A_{12} & A_{13}  \\
  A_{21} & A_{22} & A_{23}  \\
  A_{31} & A_{32} & A_{33}      
\end{array}
\right| \\
  &=&   
  A_{11} 
  \left|
\begin{array}{cc}
  A_{22} & A_{23}  \\
  A_{32} & A_{33} 
\end{array}
\right|
-
A_{12}
\left|
\begin{array}{cc}
  A_{21} & A_{23}  \\
  A_{31} & A_{33} 
\end{array}
\right|
+
A_{13}
\left|
\begin{array}{cc}
  A_{21} & A_{22}  \\
  A_{31} & A_{32} 
\end{array}
\right|
 \end{eqnarray} 
 
With the above introduce of determinant, the Cramer's rule can be described as follows. For a linear equation system $\mathbf{Ax}=\mathbf{b}$, the solution is given by 
  \begin{equation}
  x_i = \frac{det{A_i}}{det{A}}
  \end{equation}
where $A_i$ is the matrix formed by replacing the $i$-th column of $A$ with the column vector $\mathbf{b}$. For example, for a $3 \times 3$ system,

 \begin{equation}
x_1 = \frac{
 \left|
\begin{array}{ccc}
  b_1 & A_{11} & A_{13}  \\
  b_2 & A_{21} & A_{23}  \\
  b_3 & A_{31} & A_{33}      
\end{array}
\right|
}{D} 
 \end{equation}

 \begin{equation}
x_2 = \frac{
 \left|
\begin{array}{ccc}
  A_{11} & b_1 & A_{13}  \\
  A_{21} & b_2 & A_{23}  \\
  A_{31} & b_3 & A_{33}      
\end{array}
\right|
}{D} 
 \end{equation}
 
  \begin{equation}
x_2 = \frac{
 \left|
\begin{array}{ccc}
  A_{11} & A_{13} & b_1  \\
  A_{21} & A_{23} & b_2  \\
  A_{31} & A_{33} & b_3     
\end{array}
\right|
}{D} 
 \end{equation}
 
Cramer's rule has very little use in practice because of excessive computing time when the system gets large. For demonstration purpose, the following code solves a linear equation system with both the Cramer's rule and the "linalg" module in Numpy. The determinant is calculated with linalg's "det" function. The solutions are compared.

In [1]:
import numpy as np
from numpy import linalg
import sys

#replace the col-th column with b vector and assign
#it to array C
def replace_column(col, b, A, C):
    if(b.shape[0]!=A.shape[0]):
        sys.exit("The sizes of vector b and array A are not compatible.")
        
    if(A.shape[0]!=A.shape[1]):
        sys.exit("A is not a square matrix!")
        
    n = A.shape[0]
    
    #copy matrix A to C
    np.copyto(C, A) 
    
    #replace the col-th column with the vector b
    for i in range(0,n):
        C[i,col] = b[i]
    
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

C = np.zeros((len(b),len(b)))

sol = []
for i in range(0,len(b)):
    replace_column(i,b,A,C)
    sol.append(round(linalg.det(C)/linalg.det(A),8))

print("Solution from the Cramer's rule =    ", sol)

x = np.linalg.solve(A,b)      #solve with the "solve(...)" function in Numpy.
print("Solution from np.linalg.solve(...) = ", x)

Solution from the Cramer's rule =     [0.22368421, -0.06578947, 0.48684211]
Solution from np.linalg.solve(...) =  [ 0.22368421 -0.06578947  0.48684211]



### Gaussian elimination method

The Gaussina elimination method is due to the German mathematician Carl Friedrich Gauss. It is a direct solution method, which is probably the earliest linear equation system solver. Although it is old, it is still used in many linear equation system solver packages. The basic idea of Gaussian elimination method is to combine equations together to eliminate unknowns, and eventually get the solutions one by one.

The following example shows the idea. Use the elimination of unknowns to solve the $2\times 2$ system:
\begin{eqnarray*}
2 x_1 + 3 x_2 &=& 1 \\
4 x_1 -5 x_2 &=& 6
\end{eqnarray*}
Solution: (insert manual solution here)


As can be observed in the example above, manual elimination of unknowns, especially for large systems, is tedious. However, the solution procedure can be formalized and coded in a computer program. We will show such implementation in Python later. In general, the Gaussian elimination method consists of three steps:
- form the augmented matrix $[A|b]$ (optional; it is only for the ease of tracking operations)
- forward elimination to reduce the system to an upper triangle system
- backward substitution| to find the unknowns starting from the last equation.

We start by assuming the linear equation system has the form of
\begin{equation}
 \begin{bmatrix}
  a_{11} & a_{12}  & a_{13} & \cdots & a_{1n} \\
  a_{21} & a_{22}  & a_{23} & \cdots & a_{2n} \\
  a_{31} & a_{32}  & a_{33} & \cdots & a_{3n} \\    
  \vdots & \vdots  & \vdots & \ddots & \vdots\\
  a_{n1} & a_{n2}  & a_{n3} & \cdots & a_{nn}
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
  \begin{bmatrix}
 b_1 \\
 b_2 \\
 b_3 \\
 \vdots \\
 b_n
 \end{bmatrix}
\end{equation}

The goal of forward elimination is to reduce the system to an upper triangle system. It goes as follows:
- Firstly, eliminate $x_1$ from $2^{nd}$ to $n^{th}$ equations by
    - multiply the $1^{st}$ equation by $a_{21}/a_{11}$ and subtract it from the $2^{nd}$ equation, to form the new $2^{nd}$ equation.
    - multiply the $1^{st}$ equation by $a_{31}/a_{11}$ and subtract it from the $3^{rd}$ equation, to form the new $3^{rd}$ equation.
    - $\cdots$
    - multiply the $1^{st}$ equation by $a_{n1}/a_{11}$ and subtract it from the $n^{th}$ equation, to form the new $n^{th}$ equation.

\begin{equation}
 \begin{bmatrix}
  a_{11} & a_{12}  & a_{13} & \cdots & a_{1n} \\
   0     & a_{22}'  & a_{23}' & \cdots & a_{2n}' \\
   0     & a_{32}'  & a_{33}' & \cdots & a_{3n}' \\    
  \vdots & \vdots  & \vdots & \ddots & \vdots\\
   0   & a_{n2}'  & a_{n3}' & \cdots & a_{nn}'
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
  \begin{bmatrix}
 b_1 \\
 b_2' \\
 b_3' \\
 \vdots \\
 b_n'
 \end{bmatrix}
\end{equation}
The above is the (equivalent) modified system after the elimination of $x_1$. Coefficients with ' are modified. Similarly, with the modified system, eliminate $x_2$ from $3^{nd}$ to $n^{th}$ equations to get
    \begin{equation}
 \begin{bmatrix}
  a_{11} & a_{12}  & a_{13} & \cdots & a_{1n} \\
   0     & a_{22}'  & a_{23}' & \cdots & a_{2n}' \\
   0     & 0        & a_{33}'' & \cdots & a_{3n}'' \\    
  \vdots & \vdots  & \vdots & \ddots & \vdots\\
   0   & 0   & a_{n3}'' & \cdots & a_{nn}''
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
  \begin{bmatrix}
 b_1 \\
 b_2' \\
 b_3'' \\
 \vdots \\
 b_n''
 \end{bmatrix}
\end{equation}

The above is again a new equivalent system after the elimination of $x_2$. Coefficients with '' are modified. Repeat the elimination steps until reaches the last equation for $x_n$. In total, there will be $n-1$ elimination steps. The resulted equivalent system has the form of upper triangle matrix (primes are omitted for clarity)
\begin{equation}
 \begin{bmatrix}
  a_{11} & a_{12}  & a_{13} & \cdots & a_{1n} \\
   0     & a_{22}  & a_{23} & \cdots & a_{2n} \\
   0     & 0        & a_{33} & \cdots & a_{3n} \\    
  \vdots & \vdots  & \vdots & \ddots & \vdots\\
   0   & 0   &  0 & \cdots & a_{nn}
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
  \begin{bmatrix}
 b_1 \\
 b_2 \\
 b_3 \\
 \vdots \\
 b_n
 \end{bmatrix}
\end{equation}

The next step is back substitution, which solves for the unknowns from the last equation. 
- In the upper triangle matrix system, the last equation only involves $x_n$. Directly solve for $x_n$.
- With $x_n$, the $(n-1)^{th}$ equation can be used to solve for $x_{n-1}$ because it only involves $x_n$ and $x_{n-1}$.
- $\cdots$
- Keep substituting back until the first equation to solve for $x_1$.

A manual calculation example: solve the $3\times 3$ system with Gaussian elimination.
\begin{eqnarray*}
2 x_1 + 3 x_2 + 5 x_3 &=& 1 \\
4 x_1 -5 x_2 - 7 x_3 &=& 6 \\
  x_1 +2 x_2 - 3 x_3 &=& 2
\end{eqnarray*}
Solution: (insert manual calculation here)

The Gaussian elimination method described above is also sometime called the naive Gaussian elimination method because it is indeed naive and has some limitations. For example, the multiplication factor $a(i,k)/a(k,k)$ is not defined when $a(k,k)$ = 0, which may exist
- in the original matrix,
- due to the forward elimination operations.

The remedy is to do pivoting: interchange rows and columns at each step to move the coefficient with the maximum magnitude to the diagonal. There are two types of pivoting:
- complete pivoting: interchange both rows and columns.
- partial pivoting|: only interchange rows.

Pivoting not only solves the division by zero problem, but also alleviates round-off errors. Division by a small number will induce more round-off error than division by a large number. 

A manual calculation example for partial pivoting: solve the $3\times 3$ system using Gauss elimination with partial pivoting.
\begin{eqnarray*}
       3 x_2 + 5 x_3 &=& 1 \\
4 x_1 -5 x_2 - 7 x_3 &=& 6 \\
  x_1 +2 x_2 - 3 x_3 &=& 2
\end{eqnarray*}
Solution: (insert manual solution here)



This code below is a demonstration of the Gauss elimination method (without and with pivoting) for solving linear equation system.

## Gaussian elimination without pivoting

In [19]:
import numpy as np    

#perfrom Gaussian elimination (GE) for the lineary system Ax=b
#on return, the matrix A is destroyed. The solution is
#stored in x. 
def GE(A,b):
    n = len(b)
   
    # forward elimination
    for k in range(0,n-1):
        for i in range(k+1,n):
            if abs(A[k,k]) > 1E-8:
                factor = A[i,k]/A[k,k]
                A[i,:] = A[i,:] - factor*A[k,:]
                b[i] = b[i] - factor*b[k]
            else:
                sys.exit("Singular on diagonal. Pivoting is needed.")
    
    # back substitution
    x = np.zeros(n)
    for k in range(n-1,-1,-1):
        x[k] = (b[k] - np.dot(A[k,k+1:n],x[k+1:n]))/A[k,k]
    return x

#define the matrix and vector
A = np.array([[2.0,3.0,5.0], [4.0,-5.0,-7.0], [1.0,2.0,-3.0]])
b = np.array([1.0,6.0,2.0])

#call the Gaussian elimination function
x = GE(A,b)

#print out solution
print("solution = ", x)

solution =  [ 1.0942029   0.05072464 -0.26811594]


## Gauss elimination with pivoting

In [21]:
#exchange vector b's element i and j
def exchange_vector_elements(b,i,j):
    temp = b[i]
    b[i] = b[j]
    b[j] = temp

#exchange matrix A's row i and j
def exchange_matrix_rows(A,i,j,n):
    for k in range(0,n):
        temp = A[i,k]
        A[i,k] = A[j,k]
        A[j,k] = temp

#Gaussian elimination with pivoting
def GE_pivot(A,b):
    n = len(b)
   
    # forward elimination
    for k in range(0,n-1):
        #Do we need to interchange rows?
        max_val = max(abs(A[k+1:n,k]))        #max value for coeff. down below
        max_ind = np.argmax(abs(A[k+1:n,k]))  #max value's index
        
        if(abs(A[k,k]) < max_val):
            exchange_vector_elements(b,k,k+1+max_ind)
            exchange_matrix_rows(A,k,k+1+max_ind,n)
           
        for i in range(k+1,n):
            if abs(A[k,k]) > 1E-8:
                factor = A[i,k]/A[k,k]
                A[i,:] = A[i,:] - factor*A[k,:]
                b[i] = b[i] - factor*b[k]
    
    # back substitution
    x = np.zeros(n)
    for k in range(n-1,-1,-1):
        x[k] = (b[k] - np.dot(A[k,k+1:n],x[k+1:n]))/A[k,k]
    return x

A = np.array([[0.0,3,5], [4,-5,-7], [1,2,-3]])
b = np.array([1.0,6,2])

x = GE_pivot(A,b)

#print out solution
print("solution = ", x)

solution =  [1.8875 0.1875 0.0875]


As a check, solving the same linear system with Numpy. The solution should be the same as above. 

In [4]:
import numpy as np

A = np.array([[0.0,3,5], [4,-5,-7], [1,2,-3]])
b = np.array([1.0,6,2])
x = np.linalg.solve(A, b)

print(x)

[1.8875 0.1875 0.0875]


#### Scaling of linear equations

A linear equation can be scaled without changing its mathematical meaning. For example, for a linear equation as follows,
   \begin{equation}
   1.2 x_1 + 2.8 x_2 =1.2
\end{equation}     
multiply both sides by 1000 to get
\begin{equation}
   1200 x_1 + 2800 x_2 =1200
\end{equation}     
Both equations are equivalent. There are many circumstances that the scaling issue will arise. For example, 
- the use of different units
- mathematical manipulation (like the example above).

One way to get rid of the non-uniqueness is to do normalization: divide the row by its coefficient with the maximum magnitude. For example,  
\begin{equation}
   (1.2/2.8) x_1 + x_2 = (1.2/2.8)
\end{equation}    

Scaling of one or more equations in a linear system does not change the theoretical solution. However, scaling may change the numerical solution, due to e.g., round-off error. Scaling also changes the matrix determinant. For example, 
the linear system 
    \begin{eqnarray*}
   3x_1 - 5x_2 & = & 3 \\
   2x_1 - 3x_2 & = & 2
   \end{eqnarray*}
has a determinant of 
\begin{equation*}
det(A) = 3*(-3) - (-5)*2 = 1
\end{equation*}
while the equivalent linear system
 \begin{eqnarray*}
   30x_1 - 50x_2 & = & 30 \\
   2x_1 - 3x_2 & = & 2
 \end{eqnarray*}
has a determinant of 
\begin{equation*}
det(A) = 30*(-3) - (-50)*2 = 10
\end{equation*}
So, without normalization, the determinant does not mean too much for comparison. In the context of this chapter, scaling may help when the magnitudes of coefficient are very different between different equations in a linear system.  Scaling can be combined with partial pivoting to determine when pivoting is necessary.

A related topic is ill-conditioned systems. An ill-condition system is not singular, but it is close to singular. Theoretically, they do have a unique solution. However, the solution is sensitive to small perturbations to the matrix coefficients. Numerically, it is due to round-off errors, which may be alleviated with double (or higher) precision.  Scaling may also help. 

The following code is to test the effect of single, double, and half precision on the results of a system with scaling inbalance. The solution should be **x** = [1.0,1.0]. But depending on what precision is used, the numerical solution may be wrong or the algorithm does not even work. To see the difference, in the line starting with "data_type", change the "data_type" to float16 (half), loat32 (single), or, float64 (double). You will see that for the same system, when half precision is used, the Gaussian elimination algorithm fails; when single precision is used, it gives wrong solution; only when double precision is used, it gives the correct solution.

In [26]:
import numpy as np    

#perfrom Gaussian elimination for the lineary system Ax=b
#on return, the matrix A is destroyed. The solution is
#stored in x. 
def GE(A,b):
    n = len(b)
   
    # forward elimination
    for k in range(0,n-1):
        for i in range(k+1,n):
            if abs(A[k,k]) > 1E-8:
                factor = A[i,k]/A[k,k]
                A[i,:] = A[i,:] - factor*A[k,:]
                b[i] = b[i] - factor*b[k]
    
    # back substitution
    x = np.zeros(n)
    for k in range(n-1,-1,-1):
        x[k] = (b[k] - np.dot(A[k,k+1:n],x[k+1:n]))/A[k,k]
    return x

#define the matrix and vector
data_type=np.float64   #define the precision, float16 (half), loat32 (single), or, float64 (double)
A = np.array([[2.0,1e8], [1.0,1.0]],dtype=data_type)
b = np.array([1e8,2.0],dtype=data_type)

#call the Gauss elimination function
x = GE(A,b)

#print out solution
print("solution = ", x)

A = np.array([[2.0e-8,1], [1.0,1.0]],dtype=data_type)
b = np.array([1,2.0],dtype=data_type)

#call the Gauss elimination function
x = GE(A,b)

#print out solution
print("solution = ", x)

solution =  [1.00000002 0.99999998]
solution =  [1.00000002 0.99999998]


The following demonstrates the sensitiviy of an ill-conditioned system. Two systems are solved. One is a slight pertubation to the other. The use of half, single, and double precisions affects the solution. The solution should be $x=[1,1]$. However, a slight pertubation may give much different solutions for an ill-conditioned system. 

In [27]:
import numpy as np    

#perfrom Gaussian elimination for the lineary system Ax=b
#on return, the matrix A is destroyed. The solution is
#stored in x. 
def gaussian_elimination(A,b):
    n = len(b)
   
    # Forward elimination
    for k in range(0,n-1):
        for i in range(k+1,n):
            if abs(A[k,k]) > 1E-8:
                factor = A[i,k]/A[k,k]
                A[i,:] = A[i,:] - factor*A[k,:]
                b[i] = b[i] - factor*b[k]
    
    # Back substitution
    x = np.zeros(n)
    for k in range(n-1,-1,-1):
        x[k] = (b[k] - np.dot(A[k,k+1:n],x[k+1:n]))/A[k,k]
    return x

#define the matrix and vector
data_type=np.float16   #or float16, float32, float64

A = np.array([[2.0,1.0], [1.99,0.99]],dtype=data_type)
b = np.array([3,2.98],dtype=data_type)

#call the Gaussian elimination function
x = gaussian_elimination(A,b)

#print out solution
print("solution for the original linear system= ", x)

#add some purturbation to the A matrix
A = np.array([[2.0,1.0], [1.991,0.99]],dtype=data_type)
b = np.array([3,2.98],dtype=data_type)

#call the Gauss elimination function
x = gaussian_elimination(A,b)

#print out solution
print("solution for the perturbed linear system = ", x)

solution for the original linear system=  [1.1 0.8]
solution for the perturbed linear system =  [0.95454545 1.09090909]


### Gauss-Jordan method

Gauss-Jordan method is a variant of the Gaussian elimination method. The main differences include:
- When an unknown $x_k$ is eliminated, it is eliminated from not only rows below, but also rows above. 
- All rows are normalized with the pivot elements such that the resulted diagonal is 1. 
- The resulted matrix at the end is an identity matrix $I$
- Solution is just the resulted right hand side vector. 
- Thus, only elimination. No back substitution needed! 

In essence, starting from the original linear equation system in the form of
\begin{equation}
 \begin{bmatrix}
  a_{11} & a_{12}  & a_{13} & \cdots & a_{1n} \\
  a_{21} & a_{22}  & a_{23} & \cdots & a_{2n} \\
  a_{31} & a_{32}  & a_{33} & \cdots & a_{3n} \\    
  \vdots & \vdots  & \vdots & \ddots & \vdots\\
  a_{n1} & a_{n2}  & a_{n3} & \cdots & a_{nn}
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
  \begin{bmatrix}
 b_1 \\
 b_2 \\
 b_3 \\
 \vdots \\
 b_n
 \end{bmatrix}
\end{equation}

the Gauss-Jordan method will make the linear system end up like the following:

\begin{equation}
 \begin{bmatrix}
   1     &    0  & 0 & \cdots & 0 \\
   0     & 1  & 0 & \cdots & 0 \\
   0     & 0        & 1 & \cdots & 0 \\    
  \vdots & \vdots  & \vdots & \ddots & \vdots\\
   0   & 0   &  0 & \cdots & 1
 \end{bmatrix}
 \begin{bmatrix}
 x_1 \\
 x_2 \\
 x_3 \\
 \vdots \\
 x_n
 \end{bmatrix}
 =
  \begin{bmatrix}
 b_1' \\
 b_2' \\
 b_3' \\
 \vdots \\
 b_n'
 \end{bmatrix}
\end{equation}

Gauss-Jordan method looks more attractive than Gaussian elimination method because it gives the final solution with only on sweep. However, Gauss-Jordan requires more operations than Gaussian elimination.

One use of Gauss-Jordan method is to inverse a matrix:
\begin{equation}
 Ax=b  \rightarrow  x = A^{-1} b
\end{equation}  
When an inverse $A^{-1}$ is available, it is efficient to solve many linear systems with the same matrix $A$ but with different $b$ vectors. To get the inverse matrix with Gauss-Jordan method, we can do the following:
- Augment the matrix with an identity matrix and then apply Gauss-Jordan. 
- The resulted left size half is an identity matrix and the right half is the inverse. 

For example, for a $3 \times 3$ system, the augmented matrix will have the form of
     \begin{equation}
\begin{bmatrix}
  a_{11} & a_{12} & a_{13} & | & 1  & 0  & 0 \\
  a_{21} & a_{22} & a_{23} & | & 0  & 1  & 0 \\
  a_{31} & a_{32} & a_{33} & | & 0  & 0  & 1   
 \end{bmatrix}
 \end{equation}
 Perform Gauss-Jordan method with the augmented matrix will result in 
\begin{equation}
\begin{bmatrix}
  1 & 0 & 0 & | & ai_{11}  & ai_{12}  & ai_{13} \\
  0 & 1 & 0 & | & ai_{21}  & ai_{22}  & ai_{23} \\
  0 & 0 & 1 & | & ai_{31}  & ai_{32}  & ai_{33}   
 \end{bmatrix}
 \end{equation}
the right half of which is the inverse.

## Iterative solution methods

Iterative solution methods produce a sequence of approximate solutions and hopefully this sequence converges to the true solution. As mentioned before, a solution is not guaranteed by iterative methods. In other words, an iterative method may diverge even if the linear equation system is well defined. 

Example iterative solution methods include:
- Stationary iterative methods
    - Jacobi method
    - Gauss-Seidel method
    - Successive Overrelaxation (SOR) method
- Krylov subspace methods (not covered in this book)
    - Conjugate gradient (CG) method (for symmetric matrix only)
    - Conjugate gradient squared (CGS) method
    - Generalized minimal residual (GMRES) method
    - Biconjugate gradient (BiCG) method
    - Stabilized version of biConjugate gradient (BiCGStab) method

### Jacobi method

For linear equation system 
	\begin{equation}
	\mathbf{Ax=b}
	\end{equation} 
	where the matrix $\mathbf{A}$ can be written as the sum of a diagonal matrix $\mathbf{D}$ and the remainder matrix $\mathbf{R}$, i.e.,
	\begin{equation}
	\mathbf{A = D + R}
	\end{equation}
    
\begin{equation}
D = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ 0 & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & a_{nn} \end{bmatrix} \text{ and } R = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ a_{21} & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & 0 \end{bmatrix}
\end{equation}

The Jacobi iteration is then
	\begin{equation}
	\mathbf{x}^{(k+1)} = \mathbf{D}^{-1} (\mathbf{b} - \mathbf{R} \mathbf{x}^{(k)})
	\end{equation}
where $k$ is the iteration number, $k \in [0,1,2,\cdots]$. 
	Note the inverse of the diagonal matrix $\mathbf{D}$ is easy because
	\begin{equation}
\mathbf{D}^{-1} = \begin{bmatrix} 1/a_{11} & 0 & \cdots & 0 \\ 0 & 1/a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & 1/a_{nn} \end{bmatrix} 
\end{equation}
	To start the iteration, we need an initial guess $\mathbf{x}^0$. The following code is an implementation of the Jacobi method.

In [2]:
import numpy as np    


#maximum number of iterations
max_iter = 1000

#stopping criterion
eps_c = 1e-6

#define the matrix and vector
A = np.array([[10.8,2.1,2.9], [3.1,-10.5,2.1], [-2.1,3.1,8.1]])  #diagonal domimant; it converges
#A = np.array([[1.8,2.1,2.9], [3.1,-1.5,2.1], [-2.1,3.1,2.1]])  #not diagonal dominant; it will diverge
b = np.array([6.0,-12.0,26.0])

print("A = \n", A)

#initial guess for x
x = np.array([1,1,1])
x_new = x

#extract the diagonal matrix of A
D = np.diag(np.diag(A))
print("D = \n", D)

R = A - D
print("R = \n", R)

for i in range(max_iter):
    #print("iteration ", i)
    x_new = np.linalg.inv(D).dot(b-R.dot(x))
    x=x_new
    
    error = np.linalg.norm(np.dot(A,x_new) - b)/np.linalg.norm(b)
    if(error<eps_c):
        print("converged at iteration ", i)
        break;

#print out solution
print("solution = ", x)

A = 
 [[ 10.8   2.1   2.9]
 [  3.1 -10.5   2.1]
 [ -2.1   3.1   8.1]]
D = 
 [[ 10.8   0.    0. ]
 [  0.  -10.5   0. ]
 [  0.    0.    8.1]]
R = 
 [[ 0.   2.1  2.9]
 [ 3.1  0.   2.1]
 [-2.1  3.1  0. ]]
converged at iteration  17
solution =  [-0.41699705  1.5234845   2.51870298]


### Gauss-Seidel method

The matrix notation of the Gauss-Seidel method is as follows. The matrix $\mathbf{A}$ is decomposed into a lower triangular matrix $\mathbf{L}$ and a strictly upper triangular  matrix $\mathbf{U}$: $\mathbf{A=L+U}$.
\begin{equation}
\mathbf{L} = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ a_{21} & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}, \quad \mathbf{U} = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ 0 & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & 0 \end{bmatrix}.
\end{equation}	
The original linear system can be written as
\begin{equation}
 \mathbf{Lx} = \mathbf{b} - \mathbf{Ux}
\end{equation}
and the iteration formula is
\begin{equation}
\mathbf{x}^{(i+1)} = \mathbf{L}^{-1} (\mathbf{b} - \mathbf{U} \mathbf{x}^{(i)})
\end{equation}

The following code is a sample implementation of the Gauss-Seidel method.

In [3]:
import numpy as np    

#maximum number of iterations
max_iter = 1000

#stopping criterion
eps_c = 1e-6

#define the matrix and vector
A = np.array([[10.8,2.1,2.9], [3.1,-10.5,2.1], [-2.1,3.1,8.1]])  #diagonal domimant; it converges
#A = np.array([[1.8,2.1,2.9], [3.1,-1.5,2.1], [-2.1,3.1,2.1]])  #not diagonal dominant; it will diverge
b = np.array([6.0,-12.0,26.0])

print("A = \n", A)

#initial guess for x
x = np.array([1,1,1])
x_new = x

#extract the lower and strictly upper triangular matrices L and U
#see documentation for the functions tril and triu in Numpy.
L = np.tril(A,0)
U = np.triu(A,1)

print("L = \n", L)
print("U = \n", U)

for i in range(max_iter):
    #print("iteration ", i)
    x_new = np.linalg.inv(L).dot(b-U.dot(x))
    x=x_new
    
    error = np.linalg.norm(np.dot(A,x_new) - b)/np.linalg.norm(b)
    if(error<eps_c):
        print("converged at iteration ", i)
        break;

#print out solution
print("solution = ", x)

A = 
 [[ 10.8   2.1   2.9]
 [  3.1 -10.5   2.1]
 [ -2.1   3.1   8.1]]
L = 
 [[ 10.8   0.    0. ]
 [  3.1 -10.5   0. ]
 [ -2.1   3.1   8.1]]
U = 
 [[0.  2.1 2.9]
 [0.  0.  2.1]
 [0.  0.  0. ]]
converged at iteration  6
solution =  [-0.41699685  1.52348497  2.5187041 ]


### Successive over-relaxation (SOR) method

The matrix notation of the Successive over-relaxation (SOR) method is as follows. The matrix $\mathbf{A}$ is decomposed into a strictly lower triangular matrix $\mathbf{L}$, a strictly upper triangular matrix $\mathbf{U}$ and a diagonal matrix $\mathbf{D}$: $\mathbf{A=L+U+D}$.
\begin{equation}
\mathbf{L} = \begin{bmatrix} 0 & 0 & \cdots & 0 \\ a_{21} & 0 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\a_{n1} & a_{n2} & \cdots & 0 \end{bmatrix}, \quad \mathbf{U} = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ 0 & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & 0 \end{bmatrix}, \quad \mathbf{D} = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ 0 & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & a_{nn} \end{bmatrix}
\end{equation}	
The SOR iteration can be written as
\begin{equation}
\mathbf{(D+\omega L)x}^{(i+1)} = \mathbf{-[(1-\omega )L+U]\mathbf{x}^{(i)}}+\mathbf{b}
\end{equation}
Try to change the value of relaxation coefficient $\mathbf{\omega}$ to see the convergence speed.

In [10]:
import numpy as np    


#maximum number of iterations
max_iter = 1000

#stopping criterion
eps_c = 1e-6

#define the matrix and vector
A = np.array([[10.8,2.1,2.9], [3.1,-10.5,2.1], [-2.1,3.1,8.1]])  #diagonal domimant; it converges
#A = np.array([[1.8,2.1,2.9], [3.1,-1.5,2.1], [-2.1,3.1,2.1]])  #not diagonal dominant; it will diverge
b = np.array([6.0,-12.0,26.0])

print("A = \n", A)

#initial guess for x
x = np.array([1,1,1])
x_new = x
# the relaxation coefficient 
w = 1.5

#extract the lower and strictly upper triangular matrices L and U
#see documentation for the functions tril and triu in Numpy.
L = np.tril(A,-1)
U = np.triu(A,1)
D = np.diag(np.diag(A))
print("L = \n", L)
print("U = \n", U)
print("D = \n", D)

for i in range(max_iter):
    #print("iteration ", i+1)
    x_new = np.linalg.inv(D+w*L).dot(b-((1-w)*L+U).dot(x))
    x=x_new
    
    error = np.linalg.norm(np.dot(A,x_new) - b)/np.linalg.norm(b)
    if(error<eps_c):
        print("converged at iteration ", i)
        break;

#print out solution
print("solution = ", x)

A = 
 [[ 10.8   2.1   2.9]
 [  3.1 -10.5   2.1]
 [ -2.1   3.1   8.1]]
L = 
 [[ 0.   0.   0. ]
 [ 3.1  0.   0. ]
 [-2.1  3.1  0. ]]
U = 
 [[0.  2.1 2.9]
 [0.  0.  2.1]
 [0.  0.  0. ]]
D = 
 [[ 10.8   0.    0. ]
 [  0.  -10.5   0. ]
 [  0.    0.    8.1]]
converged at iteration  8
solution =  [-0.41699489  1.52348517  2.51870138]


## Python libraries for linear equation systems

This section is an introduction of Python libraries and functionalities for solving linear equation systems. The major functionalites are implemented in Numpy's linear algebra module [linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

The following example shows how to define a simple linear equation system and solve it via calling the solving function in Numpy's "linalg" module. An example linear equation system is as follows:

\begin{equation}
\mathbf{A} \mathbf{x} = \mathbf{b}
\end{equation}

\begin{equation}
\begin{bmatrix}
1  & 3  & 2 \\
5  & 8  & 7 \\
0  & -2 & 10 
\end{bmatrix}
\begin{bmatrix}
x_0 \\
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
1 \\
4 \\
5
\end{bmatrix}
\end{equation}

Within "linalg", the "solve(...)" function solves a linear equation system by calling LAPACK's routine _gesv. So in this case, the "linalg.solve(...)" function is only a wrapper.


In [4]:
import numpy as np

A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

x = np.linalg.solve(A,b)      #solve with the "solve(...)" function in Numpy.
print("solution x = ", x)

solution x =  [ 0.22368421 -0.06578947  0.48684211]


### Factorization

LU factorization is implemented in SciPy's "linalg" pacakge. 

In [5]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

#perfrom LU decomposition which returns lu and the permutation piv.
lu, piv = lu_factor(A) 

#print(lu)
#print(piv)

#solve the linear system using the LU decomposition
#Note: you can solve many linear equation systems with the same matrix A
#but with different b vectors. You only need to do LU decomposition once. 
x = lu_solve((lu, piv), b) 

print("solution x =\n",x)

solution x =
 [ 0.22368421 -0.06578947  0.48684211]


### Inverse of a matrix

This method is not suitable for large matrices. 

In [6]:
from numpy.linalg import inv

A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

#calculate the inverse of matrix A
Ainv = inv(A)

#get the solution with the inverse
x = Ainv.dot(b)

print("solution x =\n",x)

solution x =
 [ 0.22368421 -0.06578947  0.48684211]


### Solving nonlinear equation systems

Sometime we need to solve a system of nonlinear equations. This topic is related to the solution of linear equation systems because many methods to solve nonlinear systems perform linearization and iterations. In these iterative methods, at each iteration, a linear equation system needs to be solved. 

There are several options in Python. The first one is the "fsolve(...)" function in SciPy's optimization module. We have seen the the use of this function in the root findinig chapter. In fact, the rooting finding chapter deals with only one nonlinear equation, which is a special case of nonlinear equation system (only one equation). "fsolve(...)" is a wrapper around MINPACK's hybrd and hybrj algorithms.

For example, for a nonlinear equation system as follows:
\begin{eqnarray}
x^2+y &=& 3 \\
x + e^{-y} &=& 2
\end{eqnarray}
which can be written as
\begin{eqnarray}
x^2+y -3 &=& 0 \\
x + e^{-y} -2 &=& 0
\end{eqnarray}
So the goal is make a vector function $\mathbf{f}(x,y) = 0$.

        


In [7]:
from scipy.optimize import fsolve
import math

#define the vector function
def func(p):
    x, y = p
    return (x**2+y-3, x+math.exp(-y) - 2)

#call the fsolve function with an inital guess (x,y) = (1,1)
x, y =  fsolve(func, (1, 1))

print("Soutions x and y = ", x, y)
print("residuals = ", func((x, y)))


Soutions x and y =  1.5112932598218802 0.7159926827864278
residuals =  (-3.0527136374303154e-11, -2.0531576438997945e-11)


Alternatively you can use optimize's "root(...)" function.

In [8]:
from scipy.optimize import root
import math

#define the vector function
def func(p):
    x, y = p
    
    f = [x**2+y-3, 
         x+math.exp(-y) - 2]

    return f

#call the fsolve function with an inital guess (x,y) = (1,1)
sol =  root(func, (1, 1))

print("Soutions x and y = ", sol.x)
print("residuals = ", func(sol.x))

Soutions x and y =  [1.51129326 0.71599268]
residuals =  [-3.0527136374303154e-11, -2.0531576438997945e-11]


There is also a Python package named ["Sympy"](https://www.sympy.org) for  symbolic mathematics. It provides some solution functions for solving both linear and nonlinear equation systems. 

In [9]:
from sympy import Symbol, nsolve
from sympy.functions.elementary.exponential import exp
import sympy
import mpmath
x = Symbol('x')
y = Symbol('y')
f1 = x**2+y-3
f2 = x+exp(-y) - 2

sol = (nsolve((f1, f2), (x, y), (1, 1)))

print("Soutions x and y = ", sol[0],sol[1])


Soutions x and y =  1.51129325983619 0.715992682773699


## Appendix: matrix and vector operations in Python

This part is an introduction (or review) of matrix and vector operations in Python.

The objectives are to:
* understand the basic concepts and algorithms for matrix and vector
* know how to define and perform operations on matrices and vectors in Python with Numpy
* preparation for linear equation system solution

### Matrix and vector
Previously, we already briefly discussed data types in Python, where matrix and vector were introduced. In this section, a more in-depth demonstration is given.

The topics to be covered are as follows:

* creation of vector and matrix with Numpy
* matrix operations
    * matrix addition and subtraction
    * matrix multiplication
    * matrix division/inversion
    * matrix transposition
* miscelanious topics
    * indexing of matrix and vector
    * slicing of matrix and vector
    * loop over vector elements
    * loop over matrix rows, columns, and elements

We will use Numpy to create vectors and matrices. Thus, the following will load the Numpy library as **np**.

In [1]:
%matplotlib inline
import numpy as np    

#### Creation of vector and matrix with Numpy

A vector is a list of numbers. Recall that in Python, we have the definition of a **list** which can be created with a bracket. A Python list and a Numpy vector can be defined as follows. Keep in mind Python list and Numpy vector are different, though they can be converted from one to the other. 

In [2]:
a_list = [1.2,3.5,0.7]             #define a Python list
print("a_list, type(a_list) = ", a_list, type(a_list))   #print the Python list and its type

a_vector = np.array([1.2,3.5,0.7]) #define a Numpy array
print("a_vector, type(a_vector) = ", a_vector, type(a_vector))  #print the Numpy array and its type

b_vector = np.array(a_list)        #define a Numpy array based on the Python list "a_list"    
print("b_vector = ", b_vector)     #print the Numpy array

b_list = b_vector.tolist()         #convert a Numpy array to a Python list with the "tolist()" function.
print("b_list, type(b_list) = ", b_list, type(b_list))

a_list, type(a_list) =  [1.2, 3.5, 0.7] <class 'list'>
a_vector, type(a_vector) =  [1.2 3.5 0.7] <class 'numpy.ndarray'>
b_vector =  [1.2 3.5 0.7]
b_list, type(b_list) =  [1.2, 3.5, 0.7] <class 'list'>


The creation of Numpy matrices is similar to vector, except a matrix is two-dimensional. Correspondingly, in Python, a matirx is a nested list, i.e., each element is a list. The following example shows how to create 2D list in Python, matrix with Numpy, and their relationship.

In [3]:
a_nested_list = [[1,3],[5,8]]   #create a 2D list with nested 1D list
print("a_nested_list = ", a_nested_list)            

a_matrix = np.array([[1,3],[5,8]])  #create a 2D Numpy matrix
print("a_matrix = \n", a_matrix)      

b_matrix = np.array(a_nested_list)  #create a 2D Numpy matrix based on the 2D Python list
print("b_matrix = \n", b_matrix)      

b_nested_list = b_matrix.tolist()   #convert the Numpy matrix to 2D Python list
print("b_nested_list = ", b_nested_list)  

a_nested_list =  [[1, 3], [5, 8]]
a_matrix = 
 [[1 3]
 [5 8]]
b_matrix = 
 [[1 3]
 [5 8]]
b_nested_list =  [[1, 3], [5, 8]]


#### Matrix/vector operations

Since matries and vectors here are both defined with Numpy's **array**, they are essentially of the same type. So the operations described here for Numpy matrices and vectors are basically the same. 

#### Matrix/vector addition and subtraction

##### Addition of a scalar to a matrix/vector:

In [4]:
A = np.array([[1,3],[5,8]])  #create a 2D Numpy matrix
print("A = \n", A)      

B = A + 3                    #element-wise addition; it is the same as B = 3 + A
print("B = A + 3 = \n", B)      

a = np.array([1,4,6])        #create a Numpy vector
print("a = ", a)

b = a - 2                    #element-wise subtraction
print("b = a - 2 = ", b)

A = 
 [[1 3]
 [5 8]]
B = A + 3 = 
 [[ 4  6]
 [ 8 11]]
a =  [1 4 6]
b = a - 2 =  [-1  2  4]


##### Addition and subtraction of two matrices or vectors

In [5]:
A = np.array([[1,3],[5,8]])   #define two matrices
B = np.array([[0,2],[1,3]])

C = A + B                     #addition of two matrices; same as C = B + A
print("C = A + B = \n", C)

D = A - B                     #addition of two matrices; NOT same as C = B - A
print("D = A - B = \n", D)

a = np.array([3,5,9])     #define two vectors
b = np.array([-1,8,2.4])

c = a + b
print("c = a + b = ", c)

C = A + B = 
 [[ 1  5]
 [ 6 11]]
D = A - B = 
 [[1 1]
 [4 5]]
c = a + b =  [ 2.  13.  11.4]


#### Multiplication of a scalar with matrix or vector

The following example is for matrix. For vector, it is very similar.

In [6]:
A = np.array([[1,3],[5,8]])   #define matrix
print("A = \n", A)

B = 2.0*A                     #multiply the matrix by 2.0; same as B = A*2.0
print("B =2.0*A = \n", B )

C = A/3.0                     #divide the matrix by 3.0; 
print("C = A/3.0 = \n", C)

D = 3.0/A
print("D = 3.0/A = \n", D)    #divide 3.0 by each element of the matrix

A = 
 [[1 3]
 [5 8]]
B =2.0*A = 
 [[ 2.  6.]
 [10. 16.]]
C = A/3.0 = 
 [[0.33333333 1.        ]
 [1.66666667 2.66666667]]
D = 3.0/A = 
 [[3.    1.   ]
 [0.6   0.375]]


#### Matrix-Matrix, Matrix-Vector, and Vector-Vector Multiplications  

Again, since Numpy matrix and vector are both arrays, the multiplication defined here are similar, regardless it is matrix-matrix, matrix-vector, or vector-vector multiplications. Keep in mind the dimensions of the two operands should conform. For example, we have two arrays $A_{r_a \times c_a}$ and $B_{r_b \times c_b}$, where $r_a$ and $c_a$ are the number of rows and columns of array $A$, respectively. $r_b$ and $c_b$ are similarly defined for array $B$. The multiplication $A_{r_a \times c_a} \times B_{r_b \times c_b}$ is valid only when $c_a=r_b$. The resulted matrix should be $C_{r_a \times c_b}$.

The rules for the above multiplications are defined in linear algebra and they are not repeated here. The following examples show how to perform these multiplications in Python with Numpy.

The matrix multiplication in Numpy is implemented in the "**dot(...)**" function. One should not confuse this with the "*" operator. For $A*B$, it will perform element-wise multiplication, not matrix multiplication. The difference is shown in the following example. 

In [7]:
A = np.array([[1,3],[5,8]])   #define two matrices
B = np.array([[0,2],[1,3]])

c = np.array([0.2, 3.5])      #define two vectors
d = np.array([-2.3,0.7])

print("A*B = \n",A*B)         #this is element-wise multiplication, not matrix multiplication.
print("np.dot(A,B) = \n", np.dot(A,B)) #matrix-matrix multiplication with "dot(...)"
print("A.dot(B) = \n", A.dot(B))       #or matrix-matrix multiplication with "dot(...)"

print("np.dot(A,c) = \n",np.dot(A,c)) #matrix-vector multiplication
print("A.dot(c) = \n",A.dot(c))       #or matrix-vector multiplication

print("np.dot(c,d) = ", np.dot(c,d))  #vector-vector multiplication
print("c.dot(d) = ", c.dot(d))  #or vector-vector multiplication

A*B = 
 [[ 0  6]
 [ 5 24]]
np.dot(A,B) = 
 [[ 3 11]
 [ 8 34]]
A.dot(B) = 
 [[ 3 11]
 [ 8 34]]
np.dot(A,c) = 
 [10.7 29. ]
A.dot(c) = 
 [10.7 29. ]
np.dot(c,d) =  1.9899999999999998
c.dot(d) =  1.9899999999999998


#### Matrix inversion
The inversion of a matrix is defind as $A \times A^{-1} = A^{-1} \times A = I$, where $I$ is an identify matrix. Inversion is only defined for square matrices. Inversion of matrix is like division for scalars. Not all matrices can be inverted. Those not invertable are called singular matrices. 

In Numpy, the easiest way to calcuate matrix inversion is to call the "inv(...)" function in the "linalg" module. The following example shows how to use it. 

In [8]:
A = np.array([[1,3],[5,8]])   #define matrix

Ainv = np.linalg.inv(A)       #calculate the inversion of matrix A

print("A = \n", A)             
print("Ainv = \n", Ainv)
print("A.Ainv = \n", np.dot(A,Ainv))  #verify that A.Ainv = Identiy matrix.

A = 
 [[1 3]
 [5 8]]
Ainv = 
 [[-1.14285714  0.42857143]
 [ 0.71428571 -0.14285714]]
A.Ainv = 
 [[1.00000000e+00 5.55111512e-17]
 [8.88178420e-16 1.00000000e+00]]


#### Matrix transpostion

The transpose of a matrix $A$ is noted as $A^T$, which can be achieved simply with "A.T".

In [9]:
A = np.array([[1,3],[5,8]])   #define matrix

print("A = \n", A)             
print("A tranpose = \n", A.T)  #print the transpose

A = 
 [[1 3]
 [5 8]]
A tranpose = 
 [[1 5]
 [3 8]]


### Miscelanious topics

The topics in this part are useful for the understanding of materials in this chapter. 

#### Indexing of matrix and vector

Please keep in mind that Python is zero-based for arrays and lists. Thus, the index begines with 0, not 1. 

In [10]:
A = np.array([[1,3],[5,8]])   #define matrix

print("A[0,1] = ", A[0,1])    #access matix element at row 0 and column 1 (indeed the firt row and second column)

#if your index is out of range, Python will throw an "out of bounds" error.
#uncomment the following line to see error. 
#A[3,1]  #the first index 3 is out of bound.

a = np.array([1,4,5,8])   #define vector

print("a[1] = ", a[1])    #access the second element in the vector

A[0,1] =  3
a[1] =  4


One can also get one part of an array (either matrix or vector). This is called "**slicing**" in Python. 

In [11]:
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
a = np.array([1,4,5,8,11])   #define vector

print("A = \n", A)
print("a = ", a)

#get the second column of matrix A
Asub = A[:,1]
print("Asub = A[:,1] = ", Asub)

#get the third row of matrix A
Asub = A[2,:]
print("Asub = A[2,:] = ", Asub)

#get the "slice" of vector a from the second to the fourth elements
#Note: the slice [1:4] does not include the element 4. So it will only 
#get elements 1, 2, and 3.
asub = a[1:4]
print("asub = a[1:4] = ", asub)

A = 
 [[ 1  3  2]
 [ 5  8  7]
 [ 0 -2 10]]
a =  [ 1  4  5  8 11]
Asub = A[:,1] =  [ 3  8 -2]
Asub = A[2,:] =  [ 0 -2 10]
asub = a[1:4] =  [4 5 8]


An important note for "**slicing**" in Python is that it will **NOT** generate a copy of the slice. Instead, it returns a reference (i.e., memory address). To use this reference, one should use indexing with a slice object. In this way, any operation on the slice object (with indexing) will affects the original data. However, if indexing is not used, it will return a new copy.

The following example shows this effect. 

In [12]:
a = np.array([1,4,5,8,11])   #define vector

#The following code shows the use of slice with indexing [:]
print("Using slice with indexing [:]")

print("a = ", a)

#get the "slice" of vector a from the second to the fourth elements
#i.e., get elements 1, 2, and 3.
#Here asub is a slice object, i.e., a slice (part) of the original 
#vecotr a. asub is not a copy, but a reference (memory address).
asub = a[1:4]

print("asub = a[1:4] = ", asub)

#modify the value in asub with indexing [:]. This 
#will change the original data.
asub[:] = asub + 1

print("asub[:] = asub + 1 = ", asub)
print("a = ", a)

print("\n")

#The following code shows that without indexing[:], it will 
#create a copy, not a reference to the original data.
print("Using slice without indexing [:]")

a = np.array([1,4,5,8,11])   #define vector

print("a = ", a)

#get the "slice"
bsub = a[1:4]

print("bsub = a[1:4] = ", bsub)

#operate on the slice without indexing [:]. It creates a
#copy. Thus, operation will not change the original data in a.
bsub = bsub + 1

print("bsub = bsub + 1 = ", bsub)
print("a = ", a)

Using slice with indexing [:]
a =  [ 1  4  5  8 11]
asub = a[1:4] =  [4 5 8]
asub[:] = asub + 1 =  [5 6 9]
a =  [ 1  5  6  9 11]


Using slice without indexing [:]
a =  [ 1  4  5  8 11]
bsub = a[1:4] =  [4 5 8]
bsub = bsub + 1 =  [5 6 9]
a =  [ 1  4  5  8 11]


#### Loop over elements of matrix and vector

Many computing algorithms introduced in this course need to loop over the elements of an array (either matrix or vector). The following examples show how to achieve that for a vector.

In [13]:
a = np.array([1,4,5,8])   #define vector

print("vector a = ", a)

#loop over elements in array a and print it out
print("loop over vector a:")
for ele in a:
    print(ele)
    
#another way to loop over an array
#Note: we first use the "len(...)" function to get the length
#of vector a, then use the "range(...)" function to create a
#list with numbers from 0 to len(a)-1.
print("another loop over vector a:")
for i in range(len(a)):
    print(a[i])

vector a =  [1 4 5 8]
loop over vector a:
1
4
5
8
another loop over vector a:
1
4
5
8


Similarly for a matrix, we have the following example. Note the use of "enumerate" and how we get the current index of a "for" loop. In this way, we can print out the row and column numbers of each element.

In [14]:
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix

print("matrix A = \n", A)

#we can loop over each row of matrix A like this
print("loop over rows of matrix A")
for row in A:
    print(row)    #Here, row is a "slice" for matrix A corresponding to current row
    
#loop over each column of matrix A like this    
print("loop over columns of matrix A")
for col in A.T:
    print(col)    #Here, col is a "slice" for matrix A.T corresponding to current column   
    
print("loop over each element (row and then column) of matrix A")
for rowIndex, row in enumerate(A):         #loop over row
    for colIndex, ele in enumerate(row):   #then over each column in current row
        print("row = ", rowIndex, "col = ", colIndex, "val = ", ele)    #print out the current element    

matrix A = 
 [[ 1  3  2]
 [ 5  8  7]
 [ 0 -2 10]]
loop over rows of matrix A
[1 3 2]
[5 8 7]
[ 0 -2 10]
loop over columns of matrix A
[1 5 0]
[ 3  8 -2]
[ 2  7 10]
loop over each element (row and then column) of matrix A
row =  0 col =  0 val =  1
row =  0 col =  1 val =  3
row =  0 col =  2 val =  2
row =  1 col =  0 val =  5
row =  1 col =  1 val =  8
row =  1 col =  2 val =  7
row =  2 col =  0 val =  0
row =  2 col =  1 val =  -2
row =  2 col =  2 val =  10


#### Size and shape of Numpy arrays

For matrix and vector, we sometime need to know their size and dimensions. For vector, the size is its length and it only has one dimension. For matrix, it has two dimensions, i.e, row and column. 

In Numpy, the attributes and definitions of these information is as follows. For an array named **A**:
* A.ndim: number of array dimensions, e.g. =1 for vector and =2 for 2D matrix.
* A.shape: tuple of array dimenions. 
* A.size: number of total elements in the array.

The following example code shows how to access these information.

In [15]:
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

#number of dimensions
print("A.ndim = ", A.ndim)  #should be 2 because A is 2D matrix
print("b.ndim = ", b.ndim)  #should be 1 because b is a vector

#shape
print("A.shape = ", A.shape)  #should be (3,3) because A has 3 rows and 3 columns
print("b.shape = ", b.shape)  #should be 3 because b has 3 elements

#size (total number of elements)
print("A.size = ", A.size)  #should be 9 (=3x3) because A has 3 rows and 3 columns
print("b.size = ", b.size)  #should be 3 because b has 3 elements

A.ndim =  2
b.ndim =  1
A.shape =  (3, 3)
b.shape =  (3,)
A.size =  9
b.size =  3


With the information of array dimension and shape, we have anothe way to loop over elements in  arrays.

In [16]:
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix

#loop over elements in the matrix
for row_i in range(A.shape[0]):     #A.shape[0] gives number of rows
    for col_i in range(A.shape[1]): #A.shape[1] gives number of columns
        print("row,column,element = ", row_i, col_i, A[row_i, col_i])

row,column,element =  0 0 1
row,column,element =  0 1 3
row,column,element =  0 2 2
row,column,element =  1 0 5
row,column,element =  1 1 8
row,column,element =  1 2 7
row,column,element =  2 0 0
row,column,element =  2 1 -2
row,column,element =  2 2 10


#### Solve linear equation system with matrix and vector
One of the most common places to use matrix and vector is the solution of linear equation system. The following example shows how to define a simple linear equation system and solve it via calling the solving function in Numpy's "linalg" module. An example linear equation system is as follows:

\begin{equation}
\mathbf{A} \mathbf{x} = \mathbf{b}
\end{equation}

\begin{equation}
\begin{bmatrix}
1  & 3  & 2 \\
5  & 8  & 7 \\
0  & -2 & 10 
\end{bmatrix}
\begin{bmatrix}
x_0 \\
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
1 \\
4 \\
5
\end{bmatrix}
\end{equation}


In [17]:
A = np.array([[1,3,2],[5,8,7],[0,-2,10]])   #define matrix
b = np.array([1,4,5])                       #define vector

x = np.linalg.solve(A,b)      #solve with the "solve(...)" function in Numpy.
print("solution x = ", x)

solution x =  [ 0.22368421 -0.06578947  0.48684211]


#### other useful operations for matrices

* determinant
* diagonals
* trace
* eigen values and vectors

In [18]:
A = np.array([[1,3,2],[5,8,7],[0,10,1]])   #define matrix
print("A = \n", A)

#determination
print("det(A) = ", np.linalg.det(A))

#diagonals
print("diag(A) = ", np.diag(A))

#trace
print("trace(A) = ", np.trace(A))

#eigen values and vectors
eig = np.linalg.eig(A)   #eig[0]: eigen values   eig[1]: eigen vectors

print("eigen values = ", eig[0])
print("eigen vectors = \n", eig[1])

A = 
 [[ 1  3  2]
 [ 5  8  7]
 [ 0 10  1]]
det(A) =  23.0
diag(A) =  [1 8 1]
trace(A) =  10
eigen values =  [14.7243017  -0.35772746 -4.36657424]
eigen vectors = 
 [[-0.25388429  0.75807263 -0.06390746]
 [-0.78173083  0.0877419  -0.47190038]
 [-0.56959607 -0.64624086  0.87933263]]
